### ISSUE TITLE
CC Admins cannot ssh to apps in a space they are not a developer in

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/diego-ssh#10]
It seems to me that since a system administrator can pretty much do anything on the system they should be able to ssh into any application also without having to become a developer in a space.

Affects cf-222 and matching diego.

Thoughts?

**Comment by ematpl** [comment]
Hi, @youngm,

Thanks! We also noticed this issue a while ago. We think the problem is entirely in CC's access restrictions on the internal endpoint that the SSH proxy uses to authorize the connecting user, and the CAPI team has https://www.pivotaltracker.com/story/show/104490210 in their backlog to address this issue.@dieucao might have more context on the CC work that would be required. For now, as I'm sure you've observed, the workaround is for the admin user to add themselves explicitly as a SpaceDeveloper before attempting SSH access to the instance.

Best,
Eric

**Comment by youngm** [comment]
@ematpl Thanks for the tracker reference.  Being a CC issue makes sense.  Since everyone is aware of the problem I'll close this.
